### ISSUE TITLE
Tempo errado

### ISSUE THREAD

**Issue by alineai18** [natanfelles/natanfelles.github.io#2]
Oi, com licença?

Eu estava lendo seu [post sobre PHP e C++](https://natanfelles.github.io/blog/php-is-faster-than-cpp) e percebi que o senhor deve ter se enganado com o tempo nesse parágrafo:

https://github.com/natanfelles/natanfelles.github.io/blob/0bcf10d81dc151ef75d83e4f3711ffae3b34cbb2/_posts/2021-10-26-php-is-faster-than-cpp.md#L11-L13

Se o senhor quiser, posso colaborar enviando um Pull Request com o tempo certo. Vou ter tempo livre até domingo.

Só, por favor, me diga o tempo certo que o senhor quer colocar.

Obirgada!

**Comment by natanfelles** [comment]
Oi, Aline! 

Obrigado pela boa intenção.

Percebi que você sabe o tempo de vida máximo aproximado de um ser humano comum.

Gostarei muito da sua ajuda com outros problemas, mas, por horas, o tempo está certo e foi feito exatamente como solicitado.

**Comment by alineai18** [comment]
Certo.

Desculpe a demora para responder. Havia um cara me bloqueando.

Por ora, então, vou fechar essa issue. Hoje à noite, eu e o Hector vamos ao um show.

**Comment by natanfelles** [comment]
Legal. Diga a ele que mandei um abraço! 😉

**Comment by alineai18** [comment]
![Screenshot from 2021-10-31 06-35-50](https://user-images.githubusercontent.com/93167956/139576403-4644f945-0107-4c94-8cfe-2eac8511e65c.png)
